from pydantic import BaseModel
from typing import Optional
from datetime import date

class LlaveroSchema(BaseModel):
    llave_mdm : str
    llave_crm : Optional[str]
    llave_cif : Optional[str]
    tipoid : Optional[str]
    numeroid: Optional[str]
    numeroid_externo : Optional[str]
    llave_mdm : str
    
class RelperProductoSchema(BaseModel):
    rowid_object: str
    cd_tipo_documento: Optional[str]
    numero_documento: Optional[str]
    cd_fuente: Optional[str]
    cd_tipo_producto: Optional[str]
    numero_producto: Optional[str]
    cd_relacion_producto: Optional[str]
    cd_tipo_plan: Optional[str]
    fecha_inicio_relacion: Optional[date]
    fecha_fin_relacion: Optional[date]
    cd_estado_contrato: Optional[str]
    cd_estado_homologado: Optional[str]
    fecha_actualizacion: Optional[date]
    numero_documento_externo: Optional[str]
    
class rowid(BaseModel):
    rowid_object: Optional[str]
    
class cdtipodocumento(BaseModel):
    cd_tipo_documento: Optional[str]

class Peticiones(BaseModel):
    tipo_consulta: Optional[str]
    rowid_object: Optional[str]
    cd_tipo_documento: Optional[str]
    numero_producto: Optional[str]
    cd_tipo_documento: Optional[str]
    numero_documento: Optional[str]

class ContenedorResponse(BaseModel):
    rowid_object: str
    hub_state_ind: Optional[int]
    cd_segmento: Optional[str]               
    consolidation_ind: Optional[int]           
    cd_ciiu: Optional[str]                     
    cd_actividad_economica: Optional[str]      
    cd_consulta_de_extractos: Optional[str]    
    cd_genero: Optional[str]                   
    cd_ocupacion: Optional[str]                
    cd_ciudad_expedicion: Optional[str]        
    cd_tipo_interlocutor_comer: Optional[str]  
    nombre_o_razon: Optional[str]              
    nombre_corto_o_sigla: Optional[str]        
    cd_subsegmento: Optional[str]              
    tamano_comercial: Optional[int]            
    fl_persona_no_objetivo_com: Optional[str]  
    fl_persona_bloqueada: Optional[str]        
    cd_sub_ciiu: Optional[str]                 
    cd_sector: Optional[str]                   
    cd_subsector: Optional[str]                
    fl_no_aut_compartir_inform: Optional[str]  
    fl_no_aut_recibir_ofertas: Optional[str]   
    fl_no_aut_envio_msj_texto: Optional[str]   
    fl_no_aut_envio_correos: Optional[str]     
    fl_tesoreria: Optional[str]                
    cd_rol_de_negocio: Optional[str]           
    fl_realiza_ope_moneda_ext: Optional[str]   
    cd_estado_vinculacion: Optional[str]       
    cd_tipo_relacionado: Optional[str]         
    cd_relacionamiento: Optional[str]          
    cd_segmentacion_sarlaft: Optional[str]     
    cd_calificacion_interna: Optional[str]     
    cd_reporte_costos_totales: Optional[str]   
    cd_medio_actualizacion: Optional[str]      
    cd_estado_cliente: Optional[str]           
    fl_aut_recibir_ext_pdf: Optional[str]      
    cd_tratamiento: Optional[str]              
    primer_nombre: Optional[str]               
    segundo_nombre: Optional[str]              
    primer_apellido: Optional[str]             
    segundo_apellido: Optional[str]            
    cd_pais_nacimiento: Optional[str]          
    cd_departamento_nacimiento: Optional[str]  
    cd_ciudad_nacimiento: Optional[str]        
    cd_estado_civil: Optional[str]             
    cd_nivel_academico: Optional[str]          
    cd_profesion: Optional[str]                
    cd_tipo_contrato: Optional[str]            
    empresa_donde_labora: Optional[str]        
    cd_cargo_u_oficio: Optional[str]           
    cd_estrato: Optional[str]                  
    cd_tipo_vivienda: Optional[str]
    personas_a_cargo: Optional[str]            
    numero_de_hijos: Optional[int]             
    fl_pep_colombia: Optional[str]             
    fl_fallecido: Optional[str]                
    fl_secuestrado: Optional[str]              
    cd_incapaz: Optional[str]                  
    codigo_sisben: Optional[str]               
    fl_empleado: Optional[str]                 
    registro_desplazado: Optional[str]         
    cd_tipo_entidad: Optional[str]             
    cd_entidad_estatal: Optional[str]          
    cd_sociedad_comerc_o_civil: Optional[str]  
    cd_naturaleza_entidad: Optional[str]       
    cd_entidad_estatal_descent: Optional[str]  
    fl_empresa_liquidada: Optional[str]        
    fl_ley_intervencion: Optional[str]         
    cd_clase_de_grupo: Optional[str]           
    cd_tipo_documento: Optional[str]           
    numero_documento: Optional[str]            
    cd_departamento_expedicion: Optional[str]  
    cd_pais_expedicion: Optional[str]
    numero_documento_externo: Optional[str]    
    cd_estado_documento: Optional[str]         
    cd_nacionalidad: Optional[str]
    fl_nacionalidad_principal: Optional[str]
    cd_tipo_operaciones: Optional[str]
    nombre_entidad: Optional[str]
    cd_tipo_producto: Optional[str]
    numero_producto: Optional[str]
    monto_mensual: Optional[str]
    cd_moneda: Optional[str]
    cd_pais: Optional[str]
    cd_departamento: Optional[str]
    cd_ciudad: Optional[str]
    cd_tipo_documento: Optional[str]
    numero_documento: Optional[str]